name: Vulture
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  Vulture CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Vulture
      run: pip install vulture
    - name: Run Vulture
      run: vulture mayan
